version: '3.8'
services:
  app:
    build: .
    volumes:
     - .:/challenge
    ports:
     - 8000:8000
    image: app:challenge
    container_name: sqlinjection
    command: python manage.py runserver 0.0.0.0:8000